import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ModeToggle } from "@/components/theme-toggle";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ManagementLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex min-h-svh">
            <ScrollArea className="flex-1 flex flex-col p-5 gap-10 h-screen">
              <div className="flex items-center justify-between">
                <p className="font-semibold text-lg">ThreadLine.</p>
                <ModeToggle />
              </div>
              {children}
            </ScrollArea>
            <div className="bg-muted relative hidden lg:block flex-1">
              <Image
                src="/man-wearing-jacket-near-wall-in-room.jpg"
                alt="Image"
                fill
                className="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale"
              />
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
